# Generated by Django 5.2.14 on 2026-06-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('expected_reports_created', 'Нові завдання зі звітності')], max_length=50)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('sending', 'Надсилається'), ('sent', 'Надіслано'), ('failed', 'Помилка')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='reports.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='reports.reportingperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
